## Setup dependencies

In [2]:
from __future__ import print_function
import torch

In [5]:
x = torch.empty(5,3)
x

tensor([[ 0.0000e+00, -8.5899e+09, -1.7555e-11],
        [-1.5849e+29,  1.1210e-44,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [6]:
x = torch.rand(5,3)
x

tensor([[0.0381, 0.5895, 0.7543],
        [0.0955, 0.8086, 0.4682],
        [0.2061, 0.1775, 0.5105],
        [0.4946, 0.2610, 0.8736],
        [0.1340, 0.0129, 0.6645]])

In [7]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [9]:
x = torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])