## Setup dependencies

In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5,3)
x

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 4.6196e-27, 1.4013e-45],
        [4.6232e-27, 1.4013e-45, 4.6233e-27],
        [1.4013e-45, 4.6233e-27, 1.4013e-45],
        [4.6233e-27, 1.4013e-45, 4.6233e-27]])

In [3]:
x = torch.rand(5,3)
x

tensor([[0.2415, 0.9324, 0.2039],
        [0.9668, 0.1684, 0.2563],
        [0.5750, 0.5316, 0.7193],
        [0.1862, 0.8741, 0.7481],
        [0.6005, 0.3794, 0.4541]])

In [4]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])