## Setup dependencies

In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5,3)
x

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 5.6052e-45, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [3]:
x = torch.rand(5,3)
x

tensor([[0.4241, 0.6453, 0.0024],
        [0.1192, 0.7785, 0.8981],
        [0.5685, 0.6883, 0.8964],
        [0.7253, 0.1144, 0.4374],
        [0.3520, 0.4992, 0.4958]])

In [4]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])